version: '3.8'

services:
  frontend:
    image: my-nginx-image
    build: ./nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/build:/usr/share/nginx/html
    networks:
      - backend
    env_file:
      - .env

  backend:
    build: ./backend
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    depends_on:
      - elasticsearch
      - mongodb
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RUNNING_IN_CONTINAER=true
    env_file:
      - .env
    networks:
      - backend

  elasticsearch:
    build: ./elasticsearch_container
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - backend

  mongodb:
    image: mongo:4.4.8
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend
    env_file:
      - .env

volumes:
  mongodb-data:
  elasticsearch-data:

networks:
  backend:
